version: "3.9"
services:
 
  api:
    build: .
    ports:
      - "8000:8000"                 # localhost:8000 → contenedor:8000
    volumes:
      - ./app.py:/app/app.py        # hot-reload: los cambios en app.py se reflejan al instante
    environment:
      ENV: development
    # Cuando tengamos modelo, quitamos comentarios a continuacion
    # volumes:
    #   - ./app.py:/app/app.py
    #   - ./model:/app/model